# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "828f8e3449a7d86e03a67d31756aedd3"
name = "my-new-awesome-app20240509"
handle = "my-new-awesome-app20240509"
application_url = "https://wicked-garbage-junior-friend.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "echizenyayota.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wicked-garbage-junior-friend.trycloudflare.com/auth/callback",
  "https://wicked-garbage-junior-friend.trycloudflare.com/auth/shopify/callback",
  "https://wicked-garbage-junior-friend.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
